### ISSUE TITLE
Mid-semester check in

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [DukeStatSci/thesis-sp18-brown-hothand#2]
@brown-nathaniel Please respond to the following questions in a reply to this issue by Wednesday Oct 18, 5pm. Brief answers are ok.

1. What is the ultimate goal of the thesis?
2. What portion of the thesis work have you completed so far?
3. What parts of the analysis do you plan on completing by the end of the semester?
4. What sections do you expect to include in your Fall semester write up? (Note that this is due as a gitbook and PDF output on Dec 7 at 9am, I'll take a snapshot of your repo at that time.)

**Comment by mine-cetinkaya-rundel** [comment]
@brown-nathaniel Ping!

**Comment by brown-nathaniel** [comment]
1. The goal of this thesis is to investigate changes in basketball performance within games and between games, using player-tracking data from the Duke Men's Basketball team. Initially, this was going to be on the individual level, but we may look at team performance because we will have more data that way.

2. I have completed data cleaning, reading previous research on the topic, reading Professor West's textbook chapters about Dynamic Generalized Linear Models, and implementing a toy example of the model on simulated binomial data.

3. By the end of the semester, I plan on completing a DGLM and having posterior summaries of the parameters of interest at all timeunits within a game for multiple games.

4. I expect to include an abstract (without results), data (description, cleaning, etc.), procedure (DGLM), and literature review.
